name: Maven CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: ['**']

jobs:
  test:
    name: Run Maven Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven

      - name: Clean Project
        run: mvn clean

      - name: Compile Java Code
        run: mvn compile

      - name: Run JUnit and TestFX Tests
        run: xvfb-run mvn test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports
